# Generated by Django 6.0.2 on 2026-05-21 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogni_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('contacto_emergencia', models.CharField(help_text='Nombre del familiar responsable', max_length=100)),
                ('telefono_emergencia', models.CharField(max_length=15)),
                ('informe_medico_inicial', models.FileField(blank=True, null=True, upload_to='informes_medicos/')),
                ('patologias_previas', models.TextField(blank=True, help_text='Ej: Alzheimer precoz, Parkinson, etc.')),
                ('observaciones_familiares', models.TextField(blank=True, help_text='Datos que la familia considere relevantes')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
