# Generated by Django 6.0.2 on 2026-05-21 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogni_app', '0002_perfilpaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpaciente',
            name='terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
