# Generated by Django 6.0.2 on 2026-05-22 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogni_app', '0003_perfilpaciente_terapeuta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos_principales', models.TextField(help_text='¿Qué metas buscamos alcanzar a corto y mediano plazo?')),
                ('area_prioritaria', models.CharField(help_text='Ej: Memoria a corto plazo, Funciones ejecutivas, Motricidad fina...', max_length=200)),
                ('nivel_importancia', models.CharField(choices=[('ALTA', 'Prioridad Alta (Urgente / Estimulación Diaria)'), ('MEDIA', 'Prioridad Media (Mantenimiento Semanal)'), ('BAJA', 'Prioridad Baja (Seguimiento General)')], default='MEDIA', max_length=10)),
                ('actividades_recomendadas', models.TextField(help_text='Herramientas, ejercicios o talleres específicos para este paciente.')),
                ('observaciones_clinicas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_revision', models.DateField(help_text='Fecha sugerida para evaluar los avances del adulto mayor.')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_tratamiento', to=settings.AUTH_USER_MODEL)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
