# Generated by Django 6.0.2 on 2026-05-22 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogni_app', '0004_plantratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_informe', models.DateField(auto_now_add=True)),
                ('logros_destacados', models.TextField(help_text='¿En qué actividades o conductas se han observado avances?')),
                ('aspectos_por_mejorar', models.TextField(help_text='Dificultades detectadas, frustraciones o áreas que se han resistido.')),
                ('evolucion_general', models.CharField(choices=[('MEJORA_S', 'Mejora Significativa'), ('MEJORA_L', 'Mejora Leve / Estabilización'), ('SIN_CAMBIOS', 'Sin Cambios Evidentes'), ('REGRESION', 'Regresión / Requiere Intervención Médica')], default='SIN_CAMBIOS', max_length=15)),
                ('recomendaciones_proximo_mes', models.TextField(help_text='Modificaciones en los talleres, tareas para el hogar o pautas familiares.')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_progreso', to=settings.AUTH_USER_MODEL)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_redactados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
