# Generated by Django 6.0.2 on 2026-05-22 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogni_app', '0005_informeprogreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progreso',
            name='reserva',
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='PROGRAMADA', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to=settings.AUTH_USER_MODEL)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_terapeuta', to=settings.AUTH_USER_MODEL)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cogni_app.tratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='progreso',
            name='sesion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogni_app.sesion'),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
