# Generated by Django 6.0.2 on 2026-05-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogni_app', '0006_remove_progreso_reserva_sesion_progreso_sesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='estado',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada por el Paciente'), ('PROGRAMADA', 'Programada / Confirmada'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='PROGRAMADA', max_length=20),
        ),
    ]
